### ISSUE TITLE
Line 6:65

### ISSUE THREAD

**Issue by CheepScape** [yaylinda/scriptable#1]
Says j able to run because icould isnt on or something. It is on still not working

**Comment by yaylinda** [comment]
You'll need to allow iCloud permissions.

**Comment by giuliano7978** [comment]
Thanks

Giuliano

Sent from ProtonMail Mobile

Arrivato dom, dic 13, 2020 alle 23:59, Linda Zheng <notifications@github.com> ha scritto:
