### ISSUE TITLE
Error on line 193:46

### ISSUE THREAD

**Issue by MI-Studio-FreshIce** [yaylinda/scriptable#10]
2021-09-07 20:48:45: Error on line 193:46: TypeError: undefined is not an object (evaluating 'data.current.sunset')

**Comment by yaylinda** [comment]
To fix, you'll need to get an API key for the weather API. See this line: https://github.com/yaylinda/scriptable/blob/main/TerminalWidget.js#L31

**Comment by cychancw** [comment]
May I ask that why would it not working after I entered the api key?
