### ISSUE TITLE
TerminalWidget.js Event Calendar TO DO defination

### ISSUE THREAD

**Issue by DarKidoz** [yaylinda/scriptable#18]
About the PERSONAL_CALENDAR_NAME & WORK_CALENDAR_NAME, what is the format that to define iPhone calendar ? I input the '' with my calendar name, but it did not detect the iPhone calendar properly. Possible to advices the event calendar define format ?

**Comment by Apocryphilia** [comment]
> About the PERSONAL_CALENDAR_NAME & WORK_CALENDAR_NAME, what is the format that to define iPhone calendar ? I input the '' with my calendar name, but it did not detect the iPhone calendar properly. Possible to advices the event calendar define format ? 

It must be defined near the top of your script: 

  personalCalendar: '#00ffff',

You may also need to copy-paste the iCal name:

const PERSONAL_CALENDAR_NAME = 'Exact Calendar Name';

**Comment by DarKidoz** [comment]
Thanks for the update, I'll try it later :)

**Comment by yaylinda** [comment]
yep, @Apocryphilia is correct! it has to be the name EXACTLY as it is shown on the iPhone Calendar app, with the same upper/lower-cases as well.
