### ISSUE TITLE
Idea: GitHub Notifications Line

### ISSUE THREAD

**Issue by thehappydinoa** [yaylinda/scriptable#3]
![image](https://user-images.githubusercontent.com/30162978/103453318-c0ed6e80-4ca6-11eb-8d4d-457ae488456a.jpeg)

I'm working on a GitHub Notification line!

**Comment by yaylinda** [comment]
Oh nice, that's an awesome idea!

**Comment by yaylinda** [comment]
@thehappydinoa Hey there, long time no talk! If you submit a PR for this, I'd be happy to review / merge. For now I will be closing this issue :). Thanks!
