### ISSUE TITLE
I can't run TerminalWidget

### ISSUE THREAD

**Issue by harold93** [yaylinda/scriptable#5]
Hi, when I run TerminalWidget on Scriptable I have this error:
`Error on line 50:27: No file to import at Cache.`

**Comment by yaylinda** [comment]
You'll also need to create the Cache widget in Scriptable. Copy and paste the Cache.js file as a new script into Scriptable.

**Comment by harold93** [comment]
> You'll also need to create the Cache widget in Scriptable. Copy and paste the Cache.js file as a new script into Scriptable.

Thank you 😊
