### ISSUE TITLE
Calendar events not showing 

### ISSUE THREAD

**Issue by beldingd** [yaylinda/scriptable#7]
For some reason the widget says “no upcoming events” even when there are upcoming events. Scriptable has been given to Scriptable to access calendar...I changed the const at the top of the script to the names of my calendars and double checked that I didn’t make a typo.

**Comment by yaylinda** [comment]
Hmm that's weird. I'd suggest double-checking the spelling, or trying another one of these https://docs.scriptable.app/calendarevent/ functions to fetch the calendar events.

**Comment by mm41** [comment]
Hello,
first of all thanks for the awesome Widged!
I got the same exact problem, even tho there is no typo. In the logs it tells me : "Got 1 events for "Privat" tomorrow.

But it doesnt show up on the widged and keep saying "no upcoming events".

Calendar is synced with icloud, restarted my device several times, i cant seem to find the issue :/
